### ISSUE TITLE
12 -- Road Rage -- Ryan Burton

### ISSUE THREAD

**Issue by rryanburton** [tiyd-python-2015-08/assigments#191]
# Traffic simulation
## Description

Analyze the behavior of drivers on a new road to determine the optimal speed limits.
## Tasks
- [x] Blank slate
  - [x] Create a GitHub repo called `road-rage`
  - [x] Put `README.md` and `requirements.txt` files in it
  - [x] Make sure `ipython[all]`, `numpy`, and any necessary plotting libraries are in `requirements.txt`
  - [x] Make sure your `road-rage` folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [ ] Normal mode
  - [x] Create a module for the class or functions you are going to use for your simulation
  - [x] Create an IPython notebook file for gathering your data
  - [ ] Import your module into your IPython notebook and gather/plot data inside of the notebook
### Learning Objectives

After completing this assignment, you should understand:
- The use of NumPy
- Complex stochastic simulations
- Basic statistical methods
### Performance Objectives

After completing this assignment, you should be able to:
- Create complex simulations
- Speak about your findings
### Deliverables
- A Git repo called traffic-simulation containing at least:
  - `README.md` file explaining how to run your project
  - a `requirements.txt` file
  - (optional) a suite of tests for your project
  - a Python package with your code
  - an IPython notebook with your findings and plots

**Comment by rryanburton** [comment]
https://github.com/rryanburton/road-rage
it's not quite there. having a hard time getting it all together...

@powder-river 
@jamesmallen

**Comment by powder-river** [comment]
@rryanburton first comment is small, it looks like you have a method `def info_status():` thats sole purpose is to print data. In general it's probably easier just to put a print statement in the method you want to de-bug. let's talk about class set-up

as you have it, it looks like you have stored properties of your cars in the Car() class, however you are doing all of your work with cars in Road? Do you see why this approach makes life harder. Let your Car class do the actual driving, all the attributes are right there.
