### ISSUE TITLE
14 -- Express Yourself -- Ryan Burton

### ISSUE THREAD

**Issue by rryanburton** [tiyd-python-2015-08/assigments#208]
# Text Miner
## Description

Use regular expressions to validate, separate, and extract common data formats.
## Tasks
- [x] Blank slate
  - [x] Create a GitHub repo called `express-yourself`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [ ] Normal mode
  - [ ] Pass all the prewritten tests up to `HARD MODE BEGINS` in each test file
- [ ] Hard mode
  - [ ] Pass the rest of the tests
- [ ] Nightmare mode
  - [ ] Add validators, separators, and extractors with tests for:
    - [ ] URLs
    - [ ] Times
    - [ ] ISO 8601
    - [ ] Palindromes
## Objectives

After completing this assignment, you should be able to:
- Write simple regular expressions
- Recognize correct Python project layout
### Deliverables
- A Git repo called consumer-complaints containing at least:
  - `README.md` file explaining how to run your project
  - a `requirements.txt` file
  - a Python package called "textminer"
### Requirements
- No PEP8 or Pyflakes warnings or errors
## Normal Mode

Pass all the prewritten tests up to the `HARD MODE BEGINS` line in each test
file.

**Comment by rryanburton** [comment]
https://github.com/rryanburton/express-yourself

several tests passing

@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@rryanburton you had a good start but probably need some more tests for yellow. the point is "do you understand regex?" if you are having trouble still after class let's go over them in lab
