### ISSUE TITLE
16 -- Wasting Time -- Ryan Burton

### ISSUE THREAD

**Issue by rryanburton** [tiyd-python-2015-08/assigments#241]
# Wasting Time
## Description

Use the U.S. Department of Labor's data on Americans' time use for research and analysis.
## Tasks
- [x] Blank slate
  - [x] Create a GitHub repo called `atus-analysis`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
  - [x] Download the 2014 ATUS data using the `download_data.sh` script
- [x] Normal mode
  - [x] Gain an understanding of the data that is available
  - [x] Identify areas you want to compare/focus on
  - [x] Load relevant data into a notebook
  - [x] Analyze it, look for correlations, comparisons, etc.
  - [x] Present your findings in a polished notebook file (you may want to have a _scratch_ notebook for exploring, and a _final_ notebook for presentation)
### Learning Objectives

After completing this assignment, you should understand:
- How to use public data for analysis
- How to translate data from CSVs to relational databases
- How to publish your own data analysis as a notebook
### Performance Objectives

After completing this assignment, you should be able to:
- Use pandas to parse and analyze data
- Use matplotlib to chart data
- Clean data
### Deliverables
- A Git repo called atus-analysis containing at least:
  - `README.md` file explaining how to run your project
  - a `requirements.txt` file
  - an IPython notebook with your analysis
  - a suite of tests for your project
### Requirements
- Passing unit tests
- No PEP8 or Pyflakes warnings or errors

**Comment by rryanburton** [comment]
https://github.com/rryanburton/atus-analysis

@powder-river 
@jamesmallen

**Comment by powder-river** [comment]
@rryanburton good work. I appreciate your concern of those employed not spending more time with their pets.
