### ISSUE TITLE
24 -- Weather-Report -- Ryan Burton

### ISSUE THREAD

**Issue by rryanburton** [tiyd-python-2015-08/assigments#376]
## Tasks
- Yak shaving
  - [x] Create a GitHub repo called weather-report
  - [x] Create a `requirement.txt` containing the `requests` and `requests-mock` libraries and any other dependencies
- Normal mode
  - [x] Prompt the user for a ZIP code
  - [ ] Construct classes and API calls for the following features:
    - [x] Current conditions at ZIP code
    - [ ] 10 day forecast for ZIP code
    - [x] Sunrise and sunset times for ZIP code
    - [ ] Any current weather alerts for ZIP code
    - [ ] All active hurricanes (anywhere)
  - [ ] Use `requests-mock` to provide expected responses for testing purposes
  - [ ] Write test cases to cover each of the features of your classes
- Hard mode
  - [ ] Allow for city, state input in addition to ZIP code input
  - [ ] Turn your application into a Django web app
- Nightmare mode
  - [ ] Cache responses for recently made API calls

**Comment by rryanburton** [comment]
https://github.com/rryanburton/weather-report

**Comment by powder-river** [comment]
@rryanburton @jamesmallen it looks like you got started ok but never went anywhere with it. What happened?
