### ISSUE TITLE
ToDo MVC -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#387]
- Yak shaving
  - [x] Fork the [todomvc-django](https://github.com/tiyd-python-2015-08/todomvc-django) repository
- Normal mode
  - [x] Create your model(s)
  - [x] Create an API with the following endpoints:
    - GET `/api/todos/`
    - POST `/api/todos/`
    - PUT `/api/todos/{id}`
    - DELETE `/api/todos/{id}`
- Hard mode
  - [ ] Write functional tests for your API

**Comment by andrewmpierce** [comment]
https://github.com/andrewmpierce/todomvc-django
@powder-river 
Submitted! Sorry I forgot to do this last night!
