### ISSUE TITLE
25 -- ToDo MVC -- Ryan Burton

### ISSUE THREAD

**Issue by rryanburton** [tiyd-python-2015-08/assigments#390]
## Tasks
- Yak shaving
  - [x] Fork the [todomvc-django](https://github.com/tiyd-python-2015-08/todomvc-django) repository
- Normal mode
  - [x] Create your model(s)
  - [x] Create an API with the following endpoints:
    - GET `/api/todos/`
    - POST `/api/todos/`
    - PUT `/api/todos/{id}`
    - DELETE `/api/todos/{id}`
- Hard mode
  - [ ] Write functional tests for your API

**Comment by rryanburton** [comment]
https://github.com/rryanburton/todomvc-django
normal mode completed
@powder-river 
@jamesmallen
