### ISSUE TITLE
25 -- ToDo MVC -- Will Butts

### ISSUE THREAD

**Issue by Shea-Wolfe** [tiyd-python-2015-08/assigments#391]
- Yak shaving
  - [x] Fork the [todomvc-django](https://github.com/tiyd-python-2015-08/todomvc-django) repository
- Normal mode
  - [x] Create your model(s)
  - [x] Create an API with the following endpoints:
    - GET `/api/todos/`
    - POST `/api/todos/`
    - PUT `/api/todos/{id}`
    - DELETE `/api/todos/{id}`
- Hard mode
  - [x] Write functional tests for your API

**Comment by Shea-Wolfe** [comment]
@jamesmallen @powder-river 

https://github.com/Shea-Wolfe/todomvc-django

Didn't really make much headway on testing.  Still kicking around some ideas, trying to figure out requests.

Updata:  Got my tests up and running.  Not sure why I was having so many issues, I suspect small syntax errors.
